axis_linear: 1  # Left thumb stick vertical
scale_linear: 6
scale_linear_turbo: 10

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 6

enable_button: 2  # Left trigger button
enable_turbo_button: 3  # Right trigger button
